name: Build

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ${{ matrix.config.os }}
    strategy:
      fail-fast: true
      matrix:
        config:
          # - name: macOS 13
          #   # os: macos-13-large
          #   os: macos-latest
          # - name: Ubuntu
          #   os: ubuntu-latest
          - name: Windows 2022
            os: windows-2022
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Conan
        run: |
          pip install conan

      - name: Install Dependencies
        run: |
          conan profile detect
          conan install . --output-folder=build --build=missing --settings compiler.cppstd=20 --conf tools.system.package_manager:mode=install

      - name: Configure
        working-directory: build
        run: |
          cmake .. -DCMAKE_TOOLCHAIN_FILE=conan_toolchain.cmake -DCMAKE_BUILD_TYPE=Release -G "Visual Studio 17 2022" -A x64

      - name: Build
        working-directory: build
        run: |
          cmake --build . -j $(nproc)
