name: Build

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ${{ matrix.config.os }}
    strategy:
      fail-fast: true
      matrix:
        config:
          - name: macOS 13
            # os: macos-13-large
            os: macos-latest
          - name: Ubuntu
            os: ubuntu-latest
          - name: Windows 2022
            os: windows-2022
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Conan
        run: sudo pip3 install conan --prefix=/usr --upgrade

      - name: Install Dependencies
        run: |
          sudo conan profile detect
          sudo conan install . --output-folder=build --build=missing --settings compiler.cppstd=17 --conf tools.system.package_manager:mode=install
