name: Build

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: windows-2022

    steps:
      - name: Check Installed Software
        run: where git & where python & where pip
        shell: cmd

      - uses: actions/cache@v3
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}

      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Conan
        run: pip install conan

      - name: Install Dependencies
        run: |
          conan profile detect
          conan install . --output-folder=build --build=missing
