name: Build

on:
  push:
    branches:
      - main

  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ${{ matrix.config.os }}

    strategy:
      fail-fast: true

      matrix:
        config:
          #- name: macOS
          #  binary: build/carimbo
          #  os: macos-latest
          # - name: Ubuntu
          #   binary: build/carimbo
          #   os: ubuntu-latest
          - name: WebAssembly
            os: ubuntu-latest
          # - name: Windows
          #   binary: build/Release/carimbo.exe
          #   os: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Cache Dependencies
        uses: actions/cache@v3
        with:
          path: |
            ~/.conan2/p
            ~\.conan/p
          key: ${{ runner.os }}

      - name: Prepare Build Directory
        run: mkdir build

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.12"

      - name: Install Conan
        run: pip install conan

      - name: Detect Conan Profile
        run: conan profile detect --force

      - name: Detect WebAssembly Conan Profile
        if: matrix.config.name == 'WebAssembly'
        run: |
          cat > ~/.conan2/profiles/wasm <<EOF
          include(default)

          [settings]
          arch=wasm
          os=Emscripten

          [tool_requires]
          *: emsdk/3.1.44
          EOF

      - name: Install Ubuntu Dependencies
        if: matrix.config.name == 'Ubuntu'
        run: sudo apt-get install -y libegl-dev libegl1-mesa-dev libva-dev libvdpau-dev libx11-xcb-dev libfontenc-dev libxaw7-dev libxcomposite-dev libxcursor-dev libxdamage-dev libxfixes-dev libxi-dev libxinerama-dev libxmu-dev libxmuu-dev libxpm-dev libxrandr-dev libxres-dev libxss-dev libxtst-dev libxv-dev libxvmc-dev libxxf86vm-dev libxcb-render-util0-dev libxcb-xkb-dev libxcb-icccm4-dev libxcb-image0-dev libxcb-keysyms1-dev libxcb-randr0-dev libxcb-shape0-dev libxcb-sync-dev libxcb-xfixes0-dev libxcb-xinerama0-dev libxcb-dri3-dev libxcb-cursor-dev libxcb-util-dev

      - name: Install Dependencies
        if: matrix.config.name != 'WebAssembly'
        run: conan install ..  --output-folder=. --build=missing #  --settings compiler.cppstd=17 --settings build_type=Release
        working-directory: build

      - name: Install WebAssembly Dependencies
        if: matrix.config.name == 'WebAssembly'
        run: conan install ..  --output-folder=. --build=missing --profile=wasm
        working-directory: build

      - name: Configure
        run: cmake .. -DCMAKE_TOOLCHAIN_FILE="conan_toolchain.cmake" -DCMAKE_BUILD_TYPE=Release
        working-directory: build

      - name: Build
        run: cmake --build .
        working-directory: build

      - name: Upload Artifact
        uses: actions/upload-artifact@v3
        if: matrix.config.name != 'WebAssembly'
        with:
          name: ${{ matrix.config.name }}
          path: ${{ matrix.config.binary }}
          if-no-files-found: error

      - name: Prepare Pages Directory
        if: matrix.config.name == 'WebAssembly'
        working-directory: build
        run: |
          mkdir _site/
          cp carimbo.{js,wasm} _site/
          cp index.html _site/
          chmod -c -R +rX _site/

      - name: Upload Pages Artifact
        if: matrix.config.name == 'WebAssembly'
        uses: actions/upload-pages-artifact@v1
        with:
          path: build/_site

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v2
