name: Build

on:
  push:
    branches:
      - main

  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ${{ matrix.config.os }}

    strategy:
      fail-fast: true

      matrix:
        config:
          - name: macOS
            os: macos-latest
          - name: Ubuntu
            os: ubuntu-latest
          - name: WebAssembly
            script: build/carimbo.js
            os: ubuntu-latest
          - name: Windows
            os: windows-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Cache Dependencies
        uses: actions/cache@v3
        with:
          path: |
            ~/.conan2/p
            C:/Users/runneradmin/.conan2/p
          key: ${{ matrix.config.name }}-${{ hashFiles('**/conanfile.txt') }}
          restore-keys: |
            ${{ matrix.config.name }}-${{ hashFiles('**/conanfile.txt') }}
            ${{ matrix.config.name }}-

      - name: Prepare Build Directory
        run: mkdir build

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.12"

      - name: Install Build Dependencies
        if: matrix.config.name == 'Ubuntu'
        run: sudo bash -c 'apt-get update && apt-get install build-essential cmake'

      - name: Install Conan
        run: pip install conan

      - name: Detect Conan Profile
        run: conan profile detect --force

      - name: Detect WebAssembly Conan Profile
        if: matrix.config.name == 'WebAssembly'
        run: |
          cat > ~/.conan2/profiles/webassembly <<EOF
          include(default)

          [settings]
          arch=wasm
          os=Emscripten

          [tool_requires]
          *: emsdk/3.1.44
          EOF

      - name: Install Dependencies
        if: matrix.config.name != 'WebAssembly'
        run: |
          conan install .. \
            --output-folder=build \
            --build=missing \
            --settings compiler.cppstd=17 \
            --settings build_type=Release \
            --conf "tools.system.package_manager:mode=install" \
            --conf "tools.system.package_manager:sudo=True"
        working-directory: build

      - name: Install WebAssembly Dependencies
        if: matrix.config.name == 'WebAssembly'
        run: |
          conan install .. \
            --output-folder=build \
            --build=missing \
            --profile=webassembly \
            --settings compiler.cppstd=17 \
            --settings build_type=Release \
            --conf "tools.system.package_manager:mode=install" \
            --conf "tools.system.package_manager:sudo=True"
        working-directory: build

      - name: Configure
        run: cmake .. -DCMAKE_TOOLCHAIN_FILE="conan_toolchain.cmake" -DCMAKE_BUILD_TYPE=Release
        working-directory: build

      - name: Build
        run: cmake --build . --config Release --verbose
        working-directory: build
