name: Build

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ${{ matrix.config.os }}
    strategy:
      fail-fast: true
      matrix:
        config:
          - name: macOS 13
            # os: macos-13-large
            os: macos-latest
          # - name: Ubuntu
          #   os: ubuntu-latest
          # - name: Windows 2022
          #   os: windows-2022
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Cache Primes
        id: cache-primes
        uses: actions/cache@v3
        with:
          path: |
            ~/.conan2
          key: ${{ runner.os }}

      - name: Prepare Build Directory
        run: mkdir build

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.12"

      - name: Install Conan
        run: pip install conan

      - name: Detect Conan profile
        run: conan profile detect

      - name: Install Dependencies
        working-directory: build
        run: conan install ..  --output-folder=. --build=missing --settings compiler.cppstd=20 --conf tools.system.package_manager:mode=install

      - name: Configure
        working-directory: build
        run: cmake .. -DCMAKE_TOOLCHAIN_FILE=conan_toolchain.cmake -DCMAKE_BUILD_TYPE=Release

      - name: Build
        working-directory: build
        run: cmake --build . -j $(nproc)
