name: Lint

on:
  push:
    branches:
      - main

  pull_request:
    branches:
      - main

jobs:
  lint:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Cache Dependencies
        uses: actions/cache@v4
        with:
          path: |
            ~/.conan2/p
          key: ${{ runner.os }}-${{ hashFiles('**/conanfile.txt') }}

      - name: Prepare Build Directory
        run: mkdir build

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install Conan
        run: pip install conan

      - name: Detect Conan profile
        run: conan profile detect --force

      - name: Install Dependencies
        run: |
          conan install .. \
            --output-folder=build \
            --build=missing \
            --settings compiler.cppstd=17 \
            --settings build_type=Release \
            --conf "tools.system.package_manager:mode=install" \
            --conf "tools.system.package_manager:sudo=True"
        working-directory: build

      - name: Lint
        uses: cpp-linter/cpp-linter-action@v2
        id: linter
        with:
          style: file
          ignore: build
          database: build
          extra-args: -std=c++17 -Wall -Wextra

      - name: Fail Fast
        if: steps.linter.outputs.checks-failed > 0
        run: exit 1
